loom.platform=neoforge

mod.version=1.9.2

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.5+build.1
    loom.yarn_patch_neoforge=1.21+build.4

# Dependencies
    loader.neoforge=21.5.2-beta
    deps.yacl=3.6.6+1.21.5
    deps.minecraft=1.21.5
    deps.neoforge=[21.5,21.6)

# Compat
    deps.sodium_extra=mc1.21-0.5.7
    deps.iris=1.8.10+1.21.5-neoforge
    deps.serene_seasons=D6fJLkyS
    deps.enhanced_celestials=6.0.2.0-neoforge