loom.platform=neoforge

mod.version=1.6.13

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.20.6+build.1
    loom.yarn_patch_neoforge=1.20.6+build.4

# Dependencies
    loader.neoforge=20.6.119
    deps.yacl=3.6.1+1.20.6
    deps.minecraft=1.20.6
    deps.neoforge=[20.6.115,20.7)

# Compat
    deps.sodium_extra=mc1.20.6-0.5.5
	deps.iris=1.7.0+1.20.6
    deps.serene_seasons=4Rzw7f5s
    deps.enhanced_celestials=1.20.1-5.0.3.1-forge