loom.platform=neoforge

mod.version=1.13.5
mod.release=beta

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.11+build.3
    loom.yarn_patch_neoforge=1.21+build.4

# Dependencies
# use old version because arch-loom hardcoded "data/server.lzma"
    loader.neoforge=21.11.13-beta
    deps.yacl=3.8.1+1.21.11
    deps.minecraft=1.21.11
    deps.neoforge=[21.11.0,21.12)

# Compat
    deps.sodium_extra=mc1.21.11-0.8.1+neoforge
    deps.iris=1.10.4+1.21.11-neoforge
    deps.serene_seasons=yXn7Ysxn
    deps.enhanced_celestials=6.0.2.0-neoforge
    deps.sodium=mc1.21.11-0.8.2-neoforge
