import net.fabricmc.loom.task.prod.ClientProductionRunTask

plugins {
    id "net.fabricmc.fabric-loom"
    id "me.modmuss50.mod-publish-plugin"
}

base {
    archivesName = project.archives_base_name
}

def loader = "fabric"
def mcVersion = rootProject.ext.mcVersion

version = rootProject.ext.buildVersionString(loader)

loom {
    accessWidenerPath.set(project(":common").file("src/main/resources/betterclouds.accesswidener"))

    mods {
        betterclouds {
            sourceSet project(":common").sourceSets.main
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            ideConfigGenerated true
            runDir "../run/fabric-client"
            vmArgs "-XX:+AllowEnhancedClassRedefinition -Xmx2560M"
        }

        server {
            ideConfigGenerated false
            runDir "../run/fabric-server"
            vmArgs "-XX:+AllowEnhancedClassRedefinition -Xmx2560M"
        }
    }
}

dependencies {
    implementation project(":common")
    minecraft "com.mojang:minecraft:$mcVersion"

    annotationProcessor "io.github.llamalad7:mixinextras-common:${property('deps.mixin_extras')}"

    implementation "net.fabricmc:fabric-loader:${property('loader.fabric')}"
    implementation "net.fabricmc.fabric-api:fabric-api:${property('deps.fabric_api')}"

    implementation "com.terraformersmc:modmenu:${property('deps.modmenu')}"
    implementation "maven.modrinth:1eAoo2KR:${property('deps.yacl')}"

    compileOnly "maven.modrinth:KJe6y9Eu:${property('deps.fabric_seasons')}"

    include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-${loader}:${property('deps.mixinsquared')}")))
    implementation(include("io.github.llamalad7:mixinextras-fabric:${property('deps.mixin_extras')}"))

    include(implementation("gs.mclo:api:${property('deps.mclo_api')}"))
    compileOnly "maven.modrinth:Xs0XTOVv:${property('deps.distanthorizons_api')}"
    compileOnly "maven.modrinth:e0bNACJD:${property('deps.serene_seasons')}"
    compileOnly "maven.modrinth:2rL16t1O:${property('deps.enhanced_celestials')}-fabric"
    compileOnly "maven.modrinth:z2XEADmE:${property('deps.data_anchor')}-fabric"

    productionRuntimeMods "maven.modrinth:1eAoo2KR:${property('deps.yacl')}"
    productionRuntimeMods "net.fabricmc.fabric-api:fabric-api:${property('deps.fabric_api')}"
}

tasks.register("runGameTest", ClientProductionRunTask) {
    group = "loom"
    description = "Launches the Fabric client with the Fabric client game test flag."
    jvmArgs.add("-Dfabric.client.gametest")
}

processResources {
    def props = [
            version: project.version,
            loader : loader,
    ]
    props["mc_version_range"] = findProperty("deps.minecraft").toString()
            .replace("-rc-", "-rc.")
            .replace("-pre-", "-pre.")
            .split(",").collect {
        "\"~$it\""
    }.join(", ")

    props.forEach(inputs::property)

    filesMatching(["fabric.mod.json"]) {
        expand props
    }

    exclude("assets/**/*.ase")
    exclude("assets/**/*.xcf")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from(project(":common").sourceSets.main.output)
    from(rootProject.file("LICENSE").path) {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

tasks.named("sourcesJar", Jar) {
    from(project(":common").sourceSets.main.allSource)
}
