loom.platform=neoforge

mod.version=1.8.8

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.4+build.2
    loom.yarn_patch_neoforge=1.21+build.4

# Dependencies
    loader.neoforge=21.4.111-beta
    deps.yacl=3.6.2+1.21.4
    deps.minecraft=1.21.4
    deps.neoforge=[21.4.84,21.5)

# Compat
    deps.sodium_extra=mc1.21.4-0.6.1+neoforge
    deps.iris=1.8.1+1.21.3-neoforge
    deps.serene_seasons=D6fJLkyS
    deps.enhanced_celestials=6.0.2.0-neoforge