loom.platform=neoforge

mod.version=1.10.1
mod.release=alpha

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.7+build.4
    loom.yarn_patch_neoforge=1.21+build.4

# Dependencies
    loader.neoforge=21.7.4-beta
    deps.yacl=3.7.1+1.21.6
    deps.minecraft=1.21.6,1.21.7
    deps.neoforge=[21.6,21.8)

# Compat
    deps.sodium_extra=mc1.21.6-0.6.6+neoforge
    deps.iris=1.9.1+1.21.7-neoforge
    deps.serene_seasons=FuJOYqfx
    deps.enhanced_celestials=6.0.2.0-neoforge