# suppress inspection "UnusedProperty"
org.gradle.jvmargs=-Xmx2560M
# suppress inspection "UnusedProperty"
org.gradle.parallel=true
org.gradle.caching=true

fabric.loom.multiProjectOptimisation=true

# Required for some mixed Loom dependency scenarios.
loom.ignoreDependencyLoomVersionValidation=true

# Fabric Properties
loom.yarn=1.21.11+build.2
# this is optional
loom.yarn_patch_neoforge=1.21+build.6
loader.fabric=0.18.4
loader.neoforge=21.11.38-beta

maven_group = com.qendolin
archives_base_name = better-clouds

# Mod Properties
mod.version=2.0.0-alpha.1
mod.release=release

# Common Dependencies
deps.yacl=3.8.1+1.21.11
deps.minecraft=1.21.11
deps.mixin_extras=0.5.0-beta.5
deps.mixinsquared=0.3.4
deps.mclo_api=5.0.2
deps.distanthorizons_api=5.1.0
deps.neoforge=[21.11.0-beta,)

# Fabric Dependencies
deps.fabric_api=0.139.5+1.21.11
deps.modmenu=17.0.0-beta.1
deps.fabric_seasons=2.4.2-BETA+1.21
deps.sodium_options_api_fabric=fabric-1.21.5-1.0.11

# NeoForge Dependencies
deps.sodium_options_api_neoforge=neoforge-1.21.5-1.0.11

# Compat
deps.sodium_extra_fabric=mc1.21.11-0.8.3+fabric
deps.sodium_extra_neoforge=mc1.21.11-0.8.3+neoforge
deps.iris_fabric=1.10.5+1.21.11-fabric
deps.iris_neoforge=1.10.5+1.21.11-neoforge
deps.serene_seasons=10.1.0.0
deps.enhanced_celestials=6.0.2.5
deps.data_anchor=3.0.0.2
deps.sodium=mc1.21.6-0.6.13
deps.terra_firma_craft=
