# suppress inspection "UnusedProperty"
org.gradle.jvmargs=-Xmx2560M
# suppress inspection "UnusedProperty"
org.gradle.parallel=true
org.gradle.caching=true
fabric.loom.multiProjectOptimisation=true
loom.ignoreDependencyLoomVersionValidation=true
# Fabric Properties
loader.fabric=0.19.3
loader.neoforge=26.2.0.37-beta
maven_group=com.qendolin
archives_base_name=better-clouds
# Mod Properties
mod.version=1.14.3
mod.release=release
# Publish toggles
publish.fabric=true
publish.neoforge=true
# Common Dependencies
deps.mixin_extras=0.5.3
deps.mixinsquared=0.3.7-beta.1
deps.distanthorizons_api=7.0.0
deps.distanthorizons=3.1.2-b-26.2
deps.voxy=0.2.18-beta
deps.yacl=3.9.4+26.2-fabric
deps.yacl_neoforge=3.9.4+26.2-neoforge
deps.minecraft=26.2
deps.neoforge=[26.2.0.0-beta,)
# Fabric Dependencies
deps.fabric_api=0.152.1+26.2
deps.modmenu=20.0.0-beta.2
deps.fabric_seasons=2.4.2-BETA+1.21
deps.sodium_options_api_fabric=fabric-1.21.5-1.0.11
deps.serene_seasons=10.1.0.0
deps.enhanced_celestials=6.0.2.5
deps.data_anchor=3.0.0.2
deps.sodium_extra=mc1.21.11-0.8.3
deps.iris=1.11.2+26.2
deps.sodium=mc26.2-0.9.1
deps.terra_firma_craft=
