# suppress inspection "UnusedProperty"
org.gradle.jvmargs=-Xmx8G
# suppress inspection "UnusedProperty"
org.gradle.parallel=true
org.gradle.caching=true

fabric.loom.multiProjectOptimisation=true

loom.platform=[VERSIONED]
# Required bc. arch loom 1.8 isn't out yet
loom.ignoreDependencyLoomVersionValidation=true

# Fabric Properties
loom.yarn=[VERSIONED]
# this is optional
loom.yarn_patch_neoforge=
loader.fabric=0.18.1
loader.neoforge=[VERSIONED]
loader.forge=[VERSIONED]

maven_group = com.qendolin
archives_base_name = better-clouds

# Mod Properties
mod.version=[VERSIONED]
mod.release=release

# Common Dependencies
deps.yacl=[VERSIONED]
deps.minecraft=[VERSIONED]
deps.enhanced_celestials=[VERSIONED]
deps.mixin_extras=0.4.1

# Fabric Dependencies
deps.fabric_api=[VERSIONED]
deps.modmenu=[VERSIONED]

# NeoForge Dependencies

# Forge Dependencies

# Compat
deps.sodium_extra=[VERSIONED]
deps.iris=[VERSIONED]
deps.serene_seasons=[VERSIONED]
deps.fabric_seasons=[VERSIONED]
deps.sodium=
deps.terra_firma_craft=