pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = "NeoForged"
            url = "https://maven.neoforged.net/releases"
        }
        maven {
            name = "Architectury"
            url = "https://maven.architectury.dev/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "better-clouds"
include("common")
include("fabric")
include("neoforge")
