loom.platform=fabric

mod.version=1.8.8-rc.1
mod.release=beta

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.5+build.1

# Dependencies
    deps.fabric_api=0.119.5+1.21.5
    deps.modmenu=14.0.0-rc.2
    deps.yacl=3.6.6+1.21.5
    deps.minecraft=1.21.5

# Compat
    deps.sodium_extra=mc1.21-0.5.7
	deps.iris=1.8.10+1.21.5-fabric
    deps.serene_seasons=qanVNGyt
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21