loom.platform=fabric

mod.version=1.8.0
mod.release=beta

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.3+build.2

# Dependencies
    deps.fabric_api=0.107.3+1.21.3
    deps.modmenu=12.0.0-beta.1
    deps.yacl=3.6.1+1.21.2
    deps.minecraft=1.21.3

# Compat
    deps.sodium_extra=mc1.21-0.5.7
	deps.iris=1.8.0+1.21.3-fabric