loom.platform=fabric

mod.version=1.10.1
mod.release=alpha

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.6+build.1

# Dependencies
    deps.fabric_api=0.127.1+1.21.6
    deps.modmenu=15.0.0-beta.3
    deps.yacl=3.7.1+1.21.6
    deps.minecraft=1.21.6

# Compat
    deps.sodium_extra=mc1.21-0.5.7
    deps.iris=1.8.11+1.21.5-fabric
    deps.serene_seasons=qanVNGyt
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21