loom.platform=fabric

mod.version=1.8.15

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.4+build.2

# Dependencies
    deps.fabric_api=0.119.2+1.21.4
    deps.modmenu=13.0.0-beta.1
    deps.yacl=3.6.2+1.21.4
    deps.minecraft=1.21.4

# Compat
    deps.sodium_extra=mc1.21.4-0.6.1+fabric
    deps.iris=1.8.3+1.21.4-fabric
    deps.serene_seasons=qanVNGyt
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21
    deps.sodium=mc1.21.4-0.6.13-fabric