loom.platform=fabric

mod.version=1.10.7
mod.release=alpha

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.8+build.1

# Dependencies
    deps.fabric_api=0.129.0+1.21.8
    deps.modmenu=15.0.0-beta.3
    deps.yacl=3.8.0+1.21.6
    deps.minecraft=1.21.6,1.21.7,1.21.8

# Compat
    deps.sodium_extra=mc1.21.6-0.6.6+fabric
    deps.iris=1.9.1+1.21.7-fabric
    deps.serene_seasons=30NJ0mrz
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21
    deps.sodium=mc1.21.6-0.6.13-fabric