loom.platform=fabric

mod.version=1.13.5
mod.release=release

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.11+build.3

# Dependencies
    deps.fabric_api=0.140.2+1.21.11
    deps.modmenu=17.0.0-beta.1
    deps.yacl=3.8.1+1.21.11
    deps.minecraft=1.21.11

# Compat
    deps.sodium_extra=mc1.21.11-0.8.1+fabric
    deps.iris=1.10.4+1.21.11-fabric
    deps.serene_seasons=30NJ0mrz
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21
    deps.sodium=mc1.21.11-0.8.2-fabric
