loom.platform=fabric

mod.version=1.7.10

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.1+build.3

# Dependencies
    deps.fabric_api=0.115.3+1.21.1
    deps.modmenu=11.0.1
    deps.yacl=3.6.1+1.21
    deps.minecraft=1.21.0,1.21.1

# Compat
    deps.sodium_extra=mc1.21.1-0.6.0+fabric
	deps.iris=1.8.0+1.21.1-fabric
    deps.serene_seasons=UqA7miTT
    deps.enhanced_celestials=6.0.2.0-fabric
    deps.fabric_seasons=2.4.2-BETA+1.21