plugins {
	id "java"
}

base {
	archivesName = "${project.archives_base_name}-common"
}

def mcVersion = rootProject.ext.mcVersion

version = "${property('mod.version')}+${property('deps.minecraft')}-common"

tasks.named("compileJava", JavaCompile) {
	enabled = false
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

configurations {
	commonJava {
		canBeResolved = false
		canBeConsumed = true
	}
	commonResources {
		canBeResolved = false
		canBeConsumed = true
	}
}

artifacts {
	commonJava sourceSets.main.java.sourceDirectories.singleFile
	commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
