plugins {
    id "java-library"
    id "net.neoforged.moddev" version "2.0.141"
    id "me.modmuss50.mod-publish-plugin"
}

base {
    archivesName = project.archives_base_name
}

def loader = "neoforge"
def mcVersion = property('deps.minecraft')

version = rootProject.ext.buildVersionString(mcVersion)

neoForge {
    version = property("loader.neoforge").toString()

    mods {
        betterclouds {
            sourceSet(sourceSets.main)
        }
    }

    runs {
        client {
            client()
            sourceSet = sourceSets.main
            gameDirectory = layout.projectDirectory.dir("../run")
            systemProperty "forge.logging.console.level", "debug"
            ideName = "Minecraft Client (NeoForge)"
        }

        server {
            server()
            sourceSet = sourceSets.main
            gameDirectory = layout.projectDirectory.dir("../run")
            ideName = "Minecraft Server (NeoForge)"
        }
    }
}

configurations {
    commonJava {
        canBeResolved = true
        canBeConsumed = false
    }
    commonResources {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    commonJava project(path: ":common", configuration: "commonJava")
    commonResources project(path: ":common", configuration: "commonResources")
    implementation project(":common")           // for ide syntax highlighting, so it can discover :common

    annotationProcessor "io.github.llamalad7:mixinextras-common:${property('deps.mixin_extras')}"
    compileOnly "net.fabricmc:sponge-mixin:0.16.5+mixin.0.8.7"
    annotationProcessor "net.fabricmc:sponge-mixin:0.16.5+mixin.0.8.7"
    runtimeOnly "net.fabricmc:sponge-mixin:0.16.5+mixin.0.8.7"
    compileOnly "org.ow2.asm:asm-tree:9.8"
    runtimeOnly "org.ow2.asm:asm:9.8"
    runtimeOnly "org.ow2.asm:asm-tree:9.8"
    runtimeOnly "org.ow2.asm:asm-commons:9.8"
    runtimeOnly "org.ow2.asm:asm-util:9.8"
    runtimeOnly "org.ow2.asm:asm-analysis:9.8"
    annotationProcessor "org.ow2.asm:asm-tree:9.7.1"
    annotationProcessor "com.google.code.gson:gson:2.13.2"
    annotationProcessor "com.google.guava:guava:33.5.0-jre"
    compileOnly "net.fabricmc:fabric-loader:${property('loader.fabric')}"
    runtimeOnly "net.fabricmc:fabric-loader:${property('loader.fabric')}"
    compileOnly "org.apache.maven:maven-artifact:3.9.9"

    // Compile common GUI code against Yarn-named YACL classes, but run NeoForge with the NeoForge artifact.
    compileOnly "maven.modrinth:1eAoo2KR:${property('deps.yacl')}"
    runtimeOnly "maven.modrinth:1eAoo2KR:${property('deps.yacl_neoforge')}"

    compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${property('deps.mixinsquared')}"))
    implementation("com.github.bawnorton.mixinsquared:mixinsquared-${loader}:${property('deps.mixinsquared')}")
    implementation("io.github.llamalad7:mixinextras-neoforge:${property('deps.mixin_extras')}")

    // These should be included with yacl, but it doesn't work correctly, so adding them here.
    runtimeOnly "org.quiltmc.parsers:json:0.3.0"
    runtimeOnly "org.quiltmc.parsers:gson:0.3.0"

    compileOnly "maven.modrinth:YL57xq9U:${property('deps.iris_fabric')}"
    compileOnly "maven.modrinth:PtjYWJkn:${property('deps.sodium_extra_fabric')}"
    compileOnly "maven.modrinth:Es5v4eyq:${property('deps.sodium_options_api_fabric')}"

    if (!property("deps.terra_firma_craft").blank) {
        compileOnly "maven.modrinth:JaCEZUhg:${property('deps.terra_firma_craft')}"
    }

    implementation("gs.mclo:api:${property('deps.mclo_api')}")
    compileOnly "maven.modrinth:Xs0XTOVv:${property('deps.distanthorizons_api')}"
    compileOnly "maven.modrinth:e0bNACJD:${property('deps.serene_seasons')}"
    compileOnly "maven.modrinth:2rL16t1O:${property('deps.enhanced_celestials')}-fabric"
    compileOnly "maven.modrinth:z2XEADmE:${property('deps.data_anchor')}-fabric"
    if (!property("deps.sodium").blank) {
        compileOnly "maven.modrinth:AANobbMI:${property('deps.sodium')}-fabric"
    }
}

tasks.named("compileJava", JavaCompile) {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava.asFileTree.matching {
        exclude(
                "com/qendolin/betterclouds/compat/EnhancedCelestials2CompatImpl.java",
                "com/qendolin/betterclouds/mixin/runtime/SodiumGameOptionPagesMixin.java"
        )
    })
}

processResources {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)

    def props = [
            version: project.version,
            loader : loader,
    ]
    props["mc_version_range"] = findProperty("deps.minecraft").toString().split(",").collect {
        "[$it]"
    }.join(",")
    props["neoforge_version_range"] = findProperty("deps.neoforge").toString()

    props.forEach(inputs::property)

    filesMatching(["fabric.mod.json", "META-INF/mods.toml", "META-INF/neoforge.mods.toml"]) {
        expand props
    }

    exclude("fabric.mod.json")
    exclude("META-INF/mods.toml")
    exclude("assets/**/*.ase")
    exclude("assets/**/*.xcf")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.compilerArgs += ["-proc:none"]
}

java {
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from(rootProject.file("LICENSE").path) {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}
