loom.platform=fabric

mod.version=1.6.18

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.20.6+build.1

# Dependencies
    deps.fabric_api=0.100.8+1.20.6
    deps.modmenu=10.0.0
    deps.yacl=3.6.1+1.20.6
    deps.minecraft=1.20.6


# Compat
    deps.sodium_extra=mc1.20.6-0.5.5
    deps.iris=1.7.0+1.20.6
    deps.serene_seasons=pXkL38iE
    deps.enhanced_celestials=1.20.1-5.0.3.1-fabric
    deps.fabric_seasons=2.4.2-BETA+1.20.4