loom.platform=neoforge

mod.version=1.10.1
mod.release=alpha

# Fabric Properties
    # check these on https://fabricmc.net/develop/
    loom.yarn=1.21.6+build.1
    loom.yarn_patch_neoforge=1.21+build.4

# Dependencies
    loader.neoforge=21.6.5-beta
    deps.yacl=3.7.1+1.21.6
    deps.minecraft=1.21.6
    deps.neoforge=[21.6,21.7)

# Compat
    deps.sodium_extra=mc1.21-0.5.7
    deps.iris=1.8.11+1.21.5-neoforge
    deps.serene_seasons=D6fJLkyS
    deps.enhanced_celestials=6.0.2.0-neoforge