name: Game Test

on:
  pull_request:
  push:

jobs:
  client-world-load:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        modloader: [ fabric, neoforge ]
        game_version: [ 26.1 ]
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build mod
        run:
          ./gradlew build

      - name: Add mod to client
        run: |
          mkdir -p run/mods
          cp build/libs/*.jar run/mods

      - name: Install Ferium
        run: |
          curl -L https://github.com/gorilla-devs/ferium/releases/latest/download/ferium-linux-amd64 -o ferium
          chmod +x ferium
          sudo mv ferium /usr/local/bin/ferium

      - name: Download runtime mods
        run: |
          if [ "${{ matrix.mod_loader }}" = "fabric" ]; then
            ferium add fabric-api
          fi
          ferium add distanthorizons
          ferium add yacl
          ferium profile configure \
            --game-version ${{ matrix.game_version }} \
            --mod-loader ${{ matrix.modloader }} \
            --output-dir run/mods
          ferium upgrade

      - name: Load client world
        timeout-minutes: 2
        uses: headlesshq/mc-runtime-test@4.4.0
        with:
          mc: 26.1.2
          modloader: ${{ matrix.modloader }}
          regex: .*${{ matrix.modloader }}.*
          xvfb: true
          java: 25
          mc-runtime-test: ${{ matrix.modloader }}
          headlessmc-command: --jvm "-Djava.awt.headless=true"
