name: Game Test

on:
  pull_request:
  push:

jobs:
  client-world-load:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        modloader: [ fabric, neoforge ]
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Load client world
        timeout-minutes: 5
        uses: headlesshq/mc-runtime-test@3.0.0
        with:
          mc: 26.1.2
          modloader: ${{ matrix.modloader }}
          regex: .*${{ matrix.modloader }}.*
          java: 25
          mc-runtime-test: ${{ matrix.modloader }}
          headlessmc-command: --jvm "-Djava.awt.headless=true"
